# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0002_auto_20180125_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='tag',
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ManyToManyField(to='pixapp.Tag'),
        ),
    ]
