# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='Images/')),
                ('name', models.CharField(max_length=30)),
                ('descripton', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ManyToManyField(to='pixapp.tag'),
        ),
        migrations.AddField(
            model_name='images',
            name='location_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixapp.Location'),
        ),
    ]
